[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=[
  '@openzeppelin-upgradable/=lib/openzeppelin-contracts-upgradeable/',
  '@openzeppelin/=lib/openzeppelin-contracts/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
